const COURSE_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  PENDING_REVIEW: 'PENDING_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PUBLIC: 'PUBLIC',
  ARCHIVED: 'ARCHIVED',
});

const COURSE_STATUSES = Object.freeze(Object.values(COURSE_STATUS));

const COURSE_TRANSITIONS = Object.freeze({
  [COURSE_STATUS.DRAFT]: Object.freeze([COURSE_STATUS.PENDING_REVIEW, COURSE_STATUS.ARCHIVED]),
  [COURSE_STATUS.PENDING_REVIEW]: Object.freeze([COURSE_STATUS.APPROVED, COURSE_STATUS.REJECTED]),
  [COURSE_STATUS.APPROVED]: Object.freeze([COURSE_STATUS.PUBLIC, COURSE_STATUS.ARCHIVED]),
  [COURSE_STATUS.REJECTED]: Object.freeze([COURSE_STATUS.PENDING_REVIEW, COURSE_STATUS.ARCHIVED]),
  [COURSE_STATUS.PUBLIC]: Object.freeze([COURSE_STATUS.APPROVED, COURSE_STATUS.ARCHIVED]),
  [COURSE_STATUS.ARCHIVED]: Object.freeze([COURSE_STATUS.DRAFT]),
});

function canTransition(fromStatus, toStatus) {
  return Boolean(COURSE_TRANSITIONS[fromStatus]?.includes(toStatus));
}

module.exports = { COURSE_STATUS, COURSE_STATUSES, COURSE_TRANSITIONS, canTransition };
